### ISSUE TITLE
Chromosome view should not make chromosome appear to be longer than it really is

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/ZBrowse#44] opened 2022-07-26 22:00 UTC
Example:
https://zzbrowse.legumeinfo.org/?tab=Chrom&twoSpecies=y&datasets=Soybean%20GWAS&chr=Gm07&selected=35774645&window=486000&datasets2=Common%20Bean%20GWAS&chr2=Chr06&selected2=32170000&window2=492000&traitsFromOntology=y&traitsFromOntology2=y&traits=Heterodera%20glycines%20response;Reaction%20to%20heterodera%20glycines&traits2=Nematode%20damage%20resistance&neighbors=20&matched=10&intermediate=5&selectedGene=glyma.Wm82.gnm2.ann1.Glyma.08G105300&relatedRegion=Chr02%2031.86-32.48%20Mbp&macroMatched=20&macroIntermediate=10&macroMask=10&macroDistance=levenshtein
In the species 2 (common bean) view, it appears that the genes end rather abruptly
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/2009605/181119476-0d95df7f-f693-4d64-ba3e-1d4dbff4abad.png">
in fact, Chr06 is only 31977256 bp long, although the extends well beyond that, giving the illusion of a bean gene desert (we should only give illusions of a bean gene oasis)

**Comment by svengato** [comment] 2022-07-26 22:36
> chr2=Chr06&selected2=32170000&window2=492000

How did the common bean window center get to 32 Mbp? Was this returned from the GCV client?

I can try to put in a safeguard so that we never fall off either edge of the chromosome.

**Comment by adf-ncgr** [comment] 2022-07-27 00:23
I think it was a consequence of a macrosynteny block selection. No GCV clients were involved to the best of my recollection

**Comment by svengato** [comment] 2022-07-27 17:08
Hypothesis: You arrived in that state by the following steps:

1. In the Chromosome view, find the genomic linkage between soybean chromosome 8 and common bean chromosome 2.

2. Go back to the Whole Genome view, and click on a macrosynteny block toward the end of common bean chromosome 6 (syntenic with soybean chromosome 7).

3. Return to the Chromosome view, which now shows soybean chromosome 7 and common bean chromosome 6.

In this case, the issue is that step 1 set the common bean window center to 32.17 Mbp, which is valid for chromosome 2 but off the end of chromosome 6. The solution should involve resetting the window centers to those of the more recently specified macrosynteny blocks.

**Comment by svengato** [comment] 2022-07-27 17:38
That solves the problem, but I see some other things that need cleaning up. How urgent is it to get into production?

**Comment by adf-ncgr** [comment] 2022-07-27 17:45
I'm not feeling angsty about it (ie this particular issue).

**Comment by svengato** [comment] 2022-07-27 17:47
"other things that need cleaning up" = there are other ways to fall off the edge of the chromosome.

**Comment by svengato** [comment] 2022-07-27 19:43
Try it now,
  http://dev.lis.ncgr.org:50071
(development version)

**Comment by svengato** [comment] 2022-07-29 18:47
Fixed in commit 20f51c3.

**Closed as completed by svengato** 2022-07-29 18:47 UTC
